mongo:
  image: mongo:latest
  container_name: "mongo"
  ports:
    - "27017:27017"
api_calendario:
  build: .
  container_name: api_calendario
  env_file: .env
  ports:
    - "3000:3000"
  links:
    - mongo
